# Use Bitnami's PHP-FPM 8.2 image as the base image
FROM bitnami/php-fpm:8.2

## Install system packages required for Xdebug
#RUN apt-get update && apt-get install -y git
#
## Install Xdebug
#RUN apt-get update && apt-get install -y autoconf build-essential \
#    && pecl install xdebug



# Copy your Laravel application code into the container

# Set the working directory to your app
#WORKDIR /app

# Install Composer dependencies (if required)
# RUN composer install --no-interaction
#
## Set the correct permissions (adjust as needed)
#RUN chown -R daemon:daemon /app
#
## Expose the port (if your application communicates externally)
## EXPOSE <port-number>
#
## Set the user to a non-root user (Bitnami images typically use 'daemon')
#USER daemon
