version: '2.18'
services:
    mysql: #server name
        container_name: mysql8.0
        build: ./docker/mysql
        networks:
          - my_network
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/bitnami/mysql/data
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=my_password
            - MYSQL_USER=www
            - MYSQL_PASSWORD=www
            - MYSQL_DATABASE=website

    php-fpm:
        container_name: php8.2
        build: docker/php
        networks:
          - my_network
        ports:
            - "9000:9000"
        volumes:
            - .:/app
            - ./docker/php/logs:/opt/bitnami/php/logs
            - ./docker/php/etc:/opt/bitnami/php/etc
        depends_on:
            - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
      container_name: nginx1.24
      build: docker/nginx
      networks:
        - my_network
      depends_on:
        - php-fpm
        - mysql
      ports:
        - "80:8080"
        - "443:8443"
      volumes:
        - .:/app
        - ./docker/nginx/logs:/opt/bitnami/nginx/logs
        - ./docker/nginx/conf:/opt/bitnami/nginx/conf


volumes:
    mysql_data:
        driver: local
networks:
  my_network:
